### ISSUE TITLE
Rocket League

### ISSUE THREAD

**Issue by tastyhub** [ToasterUwU/flake#112]
Hi. I was checking out protondb and think I read your Rocket League [report](https://www.protondb.com/app/252950#KXPGfXiwzY). 

if that’s not you I apologize!

I’m using Bazzite as my primary OS on PC and play RL so I was surprised about your experience with Epic blocking Linux. Do you have any more information you could provide?

**Comment by ToasterUwU** [comment]
@tastyhub Hey! Yup thats me, and yes i cant enter multiplayer, only local splitscreen is allowed. 

I bough the game on Steam when it was still on there and a payed game. So maybe this is a Steam version thing specifically, which would be even more messed up in my opinion. One thing i didnt check is if its running natively and only that isnt supported anymore. I got a popup telling me that Linux and Max arent supported anymore, but maybe that just means "native ports" of that game. Let me check real quick.

**Comment by ToasterUwU** [comment]
Also, next time, just send me an email instead of making an Issue on something that has nothing to do with this, my email is in my Github Profile for everyone to see.

**Comment by ToasterUwU** [comment]
Yup, forcing it to a windows version makes that problem go away. The issue is that Steam defaults to the Linux version, which is outdated and doesnt work anymore, but there is a windows version i can run with proton, i just have to force it to use it.

**Comment by ToasterUwU** [comment]
I made a new report talking about this issue. Should be released soon.

**Comment by tastyhub** [comment]
Glad you got it sorted and sorry for not emailing you directly. I should have looked more closely.
